from __future__ import annotations

from .models import Record


SEED_RECORDS: tuple[Record, ...] = (
    Record(
        id=None,
        requirement="智能工单优先级排序",
        mr="feat: ranking pipeline with prompt guard",
        mr_url="https://git.example.com/ai-platform/workbench/-/merge_requests/1287",
        owner="林越",
        group="cos",
        lines=1860,
        efficiency=34,
        score=4.7,
        problem="领域词召回不稳，补充了评测集与回退策略",
        date="2026-07-08",
        status="已合并",
    ),
    Record(
        id=None,
        requirement="灰度发布配置生成器",
        mr="feat: rollout composer and policy preview",
        mr_url="https://git.example.com/ai-platform/workbench/-/merge_requests/1269",
        owner="顾辰",
        group="d5",
        lines=1320,
        efficiency=28,
        score=4.4,
        problem="JSON Schema 边界提示过宽，增加模板约束",
        date="2026-07-07",
        status="已合并",
    ),
    Record(
        id=None,
        requirement="接口回归用例自动补全",
        mr="test: generated contract coverage for payment APIs",
        mr_url="https://git.example.com/ai-platform/workbench/-/merge_requests/1261",
        owner="陈珂",
        group="cos",
        lines=2430,
        efficiency=41,
        score=4.8,
        problem="Mock 数据命名混乱，人工统一语义标签",
        date="2026-07-06",
        status="验证中",
    ),
    Record(
        id=None,
        requirement="研发知识库检索优化",
        mr="perf: hybrid search rerank and snippets",
        mr_url="https://git.example.com/ai-platform/workbench/-/merge_requests/1248",
        owner="苏禾",
        group="d5",
        lines=970,
        efficiency=22,
        score=4.1,
        problem="历史文档格式不一，清洗耗时高于预期",
        date="2026-07-04",
        status="已合并",
    ),
    Record(
        id=None,
        requirement="埋点指标口径校验",
        mr="feat: metric consistency assistant",
        mr_url="https://git.example.com/ai-platform/workbench/-/merge_requests/1239",
        owner="邵宁",
        group="cos",
        lines=760,
        efficiency=19,
        score=3.9,
        problem="跨端字段别名太多，仍需产品侧确认口径",
        date="2026-07-02",
        status="已合并",
    ),
    Record(
        id=None,
        requirement="前端异常聚类诊断",
        mr="feat: crash cluster insight panel",
        mr_url="https://git.example.com/ai-platform/workbench/-/merge_requests/1226",
        owner="顾辰",
        group="d5",
        lines=1510,
        efficiency=31,
        score=4.5,
        problem="堆栈相似度阈值需要结合线上样本微调",
        date="2026-06-30",
        status="验证中",
    ),
    Record(
        id=None,
        requirement="权限策略差异分析",
        mr="feat: policy diff explainer",
        mr_url="https://git.example.com/ai-platform/workbench/-/merge_requests/1212",
        owner="林越",
        group="cos",
        lines=1180,
        efficiency=26,
        score=4.3,
        problem="策略 DSL 缺少注释，生成解释需人工复核",
        date="2026-06-28",
        status="已合并",
    ),
    Record(
        id=None,
        requirement="构建失败自动诊断",
        mr="fix: ci failure classifier and hints",
        mr_url="https://git.example.com/ai-platform/workbench/-/merge_requests/1198",
        owner="陈珂",
        group="d5",
        lines=890,
        efficiency=24,
        score=4.2,
        problem="少量日志噪声误判为依赖问题",
        date="2026-06-25",
        status="已合并",
    ),
)
